name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Submit Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml --region us-central1 .
          # The "." at the end is crucial; it specifies the build context (the current directory).

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy slugseiai --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/slugseiai --platform managed --allow-unauthenticated --region us-central1
