name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'
          service_account: 'github-action@poetic-planet-449502-i0.iam.gserviceaccount.com'

      - name: 'Docker Auth'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: 'Build and Push Container'
        env:
          PROJECT_ID: poetic-planet-449502-i0
          GAR_LOCATION: us-central1
          GAR_NAME: ghaction
          REGION: us-central1
          SERVICE: virtual-baseball-coach
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build -t "${DOCKER_TAG}" --file ./backend/Dockerfile ./backend
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'virtual-baseball-coach'
          region: 'us-central1'
          image: 'us-central1-docker.pkg.dev/poetic-planet-449502-i0/ghaction/virtual-baseball-coach:${{ github.sha }}'

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
