name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger the deployment when pushing to the main branch

env:
  PROJECT_ID: "your-gcp-project-id"
  REGION: "us-central1"  # Change this to your preferred region
  SERVICE: "virtual-baseball-coach"  # Change this to your Cloud Run service name
  GAR_NAME: "ghaction"  # Google Artifact Registry name

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker to use Google Cloud's Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      # Build and push the Docker image
      - name: Build & Push Docker Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_NAME/$SERVICE:$GITHUB_SHA -f ./backend/Dockerfile ./backend
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_NAME/$SERVICE:$GITHUB_SHA

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_NAME/$SERVICE:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
